version: 0.2

phases:
  install:
    commands:
      # Fetch the unique SHA for tagging Docker images
      - SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 637423521355.dkr.ecr.ap-south-1.amazonaws.com
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started for commit $SHA
      - echo Building the Docker image...
      - docker build -t fastapi-lambda:$SHA .
      - docker tag fastapi-lambda:$SHA 637423521355.dkr.ecr.ap-south-1.amazonaws.com/milind/fastapi:$SHA
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 637423521355.dkr.ecr.ap-south-1.amazonaws.com/milind/fastapi:$SHA
      - echo Build and push completed successfully.

      # Check if the Lambda function exists to update or create it
      - echo "Running the custom shell script..."
      - chmod +x scripts/create_or_update_lambda_function.sh   # Ensure the script is executable
      - ./scripts/create_or_update_lambda_function.sh


artifacts:
  files:
    - '**/*'
  discard-paths: yes

